"""Create initial tables including bgm

Revision ID: a3e3facd0cd5
Revises: 1a31ce608336
Create Date: 2025-07-27 15:25:46.502011

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a3e3facd0cd5'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bgm',
    sa.Column('album', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bgm_album'), 'bgm', ['album'], unique=False)
    op.create_index(op.f('ix_bgm_title'), 'bgm', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bgm_title'), table_name='bgm')
    op.drop_index(op.f('ix_bgm_album'), table_name='bgm')
    op.drop_table('bgm')
    # ### end Alembic commands ###
